#!/bin/sh
#
# taskExec
#
##################################

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=taskExec.py
DAEMON=/home/yyran/DynamicEC2/daemon_vm/
DESC=daemon-taskexec


start_taskExec () {
    echo "taskExec server is starting..." 
    cd ${DAEMON}
    nohup python ${NAME} &
}

stop_taskExec () {
    echo "taskExec server is stopping..."
    killall -9 python
}

restart_taskExec () {
    stop_taskExec
    start_taskExec
}

case "$1" in
    start)
        start_taskExec
    	echo "taskExec server is started."
        ;;
    stop)
        stop_taskExec
        echo "taskExec server is stopped."
        ;;
   force-reload|reload|restart)
        echo -n "Restarting taskExec server..."
        restart_taskExec
        echo "Restart taskExec server over."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
        RETVAL=1
        ;;
esac

exit $RETVAL
